app/urls.py
from django.contrib import admin
from django.urls import path

from app.views import *

app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('signout/', signout, name='signout'),
    
    path('students/', students, name='students'),
    path('teachers/', teachers, name='teachers'),
    path('blogs/', blogs, name='blogs'),
    path('addBlog/', addBlog, name='addBlog'),
    path('blogDetails/<int:blog_id>', blogDetails, name='blogDetails'),

    
    path('approve/<int:user_id>', approve, name='approve'),
    path('refuse/<int:user_id>', refuse, name='refuse'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class myCustomUser(AbstractUser):
    username = models.CharField(max_length=20, unique="True", blank=False)
    password = models.CharField(max_length=200)
    email = models.EmailField(max_length=200, unique=True)
    userChoice = [
        ('Student', 'Student'),
        ('Teacher', 'Teacher'),
        ('Admin', 'Admin')
    ]
    userType = models.CharField(max_length=50, choices=userChoice, default='None', null=True, blank=True)

    isVarified = models.BooleanField(default=False)

    def __str__(self):
        return self.username
    
class Blog(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(myCustomUser, on_delete=models.CASCADE)
    picture = models.ImageField(blank=True)

    def __str__(self):
        return self.title

app/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.hashers import make_password, check_password, is_password_usable
from django.contrib.auth.models import User
from django.db import IntegrityError, transaction

from datetime import datetime
from django.utils import timezone

from app.models import *
# Create your views here.


def index(request):
    return render(request, 'index.html')


#log in view
def signin(request):
    if request.method == "POST":
        this_username = request.POST['username']
        this_password = request.POST['password']
        user = authenticate(username=this_username, password=this_password)
        login(request, user)
    return redirect('app:index')


#signout view
def signout(request):
    logout(request)
    return redirect('app:index')


#signup view
def signup(request):
    if request.method == "POST":
        if request.POST['password'] == request.POST['password2']:
            try:
                with transaction.atomic():
                    user_obj = myCustomUser.objects.create(
                        username = request.POST['username'],
                        email = request.POST['email'],
                        password = make_password(request.POST['password'], salt=None, hasher='default'),
                        userType = request.POST['userType'],
                    )
                    user_obj.save()
                    return redirect('app:index')
            except IntegrityError:
                print("Error")
    return render(request, 'signup.html')


#approve user view
def approve(request, user_id):
    if request.user.is_superuser or (request.user.isVarified and request.user.userType == 'Admin'):
        user = myCustomUser.objects.get(id=user_id)
        user.isVarified = True
        user.save()
    return redirect('app:index')

#refuse user view
def refuse(request, user_id):
    if request.user.is_superuser or (request.user.isVarified and request.user.userType == 'Admin'):
        user = myCustomUser.objects.get(id=user_id)
        user.isVarified = False
        user.save()
    return redirect('app:index')


#all student list view
def students(request):
    students = myCustomUser.objects.filter(userType='Student')
    return render(request, 'students.html', {'students': students})

#all teacher and admin list view
def teachers(request):
    teachers = myCustomUser.objects.filter(userType='Teacher')
    admins = myCustomUser.objects.filter(userType='Admin')
    return render(request, 'teachers.html', {'teachers': teachers, 'admins' : admins})


#all Blogs view
def blogs(request):
    blogs = Blog.objects.all()
    return render(request, 'blogs.html', {'blogs': blogs})

#blog view
def blogDetails(request, blog_id):
    blogs = Blog.objects.get(id=blog_id)
    return render(request, 'blogDetails.html', {'blogs': blogs})

#add blog
def addBlog(request):
    if request.method == "POST" and (request.user.isVarified or request.user.is_superuser):
        blog = Blog.objects.create(
            title = request.POST['title'],
            body = request.POST['body'],
            author = request.user,
            created_at = timezone.now(),
            picture = request.FILES['picture'],
        )
        blog.save()
        return redirect('app:blogs')
    return render(request, 'addBlog.html')

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <title></title>

    <meta charset="UTF-8">

  	<!-- media queary support -->
  	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

  	<!-- Latest compiled and minified CSS -->
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

  	<!-- jQuery library -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  	<!-- Popper JS -->
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  	<!-- Latest compiled JavaScript -->
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  	<!-- animated css link -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>

  	<!-- font awsome css link -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  	<!-- poppins font link -->
  	<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>

  	<!-- roboto font link -->
  	<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>

  	<!-- custom css link -->
  	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

  </head>
  <body>

    <div class="container-fluid">
      <div class="row m-0" style="padding-left: 90px; padding-right: 80px;padding-top: 10px;">
          <a href="{% url 'app:index' %}" style="font-size: 36px; font-weight: 700;">
            <span style="color:#3c97e8;">DR</span>
            <span style="color:#9bdf46;">Appoinment</span>
          </a>

        <div class="col-md-2 ml-auto">
            <div class="row m-0">
                <span class="mx-3"><img src="{% static 'imgs/phn.png' %}" style="max-height: 40px;"></span>
                <p>Call Us<br>99-222-333</p>
            </div>
        </div>

        <div class="col-md-3 ml-4">
            <div class="row m-0">
                <span class="mx-3"><img src="{% static 'imgs/phn.png' %}" style="max-height: 40px;"></span>
                <p>Address<br>221B Baker Street London, Uk</p>
            </div>
        </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light py-3" style="padding-left: 80px;padding-right: 80px;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active mx-4">
              <a class="nav-link" href="{% url 'app:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mx-4">
              <a class="nav-link" href="#">About Us</a>
            </li>
            <li class="nav-item mx-4">
                <a class="nav-link" href="#">Meet Our Doctors</a>
            </li>
            <li class="nav-item mx-4">
                <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item mx-4">
                <a class="nav-link" href="#">Feedback</a>
            </li>

            
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link mx-3" href="#">Hi {{request.user.username}}!</a>
            <li class="nav-item">
                <a href="#" class="btn nav-link" style="background-color: #9bdf46; color:white; width:100px; height:40px; border-radius:40px;">Logout</a>
            </li>
            {% else %}
            <li class="nav-item" data-toggle="modal" data-target="#loginModal">
                <a href="#" class="btn nav-link" style="background-color: #9bdf46; color:white; width:100px; height:40px; border-radius:40px;">Login</a>
            </li>
            {% endif %}
        </ul>
            
        </div>
      </nav>



    {% block content %}

    {% endblock %}







    
<!-- login modal start -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title login-modal-title" id="loginModalLabel">Welcome back</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="#">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>User name</label>
                        <input type="text" class="form-control" name="username" placeholder="User name">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>

                    <div style="height: 80px;"></div>

                    <p class="modal-forgorpass text-center">
                        <a href="#">Forgot password?</a>
                    </p>
                    <input type="submit" class="btn login-submit mt-2 ml-3" name="login" value="Login" style="background-color: #64B53B;">
                    <p class="need-acnt text-center mt-3">
                        Need an account?
                        <a href="#" class="need-acnt-signup" type="button" data-toggle="modal" data-target="#registerModal" data-dismiss="modal" aria-label="Close">
                            Sign up
                        </a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- login modal end -->

<!-- register modal start -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title reg-modal-title" id="registerModalLabel">Sign up</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body py-5">

                <a href="#" class="reg-container row pt-3 my-4 mx-auto">
                    <img src="{% static 'icons/student.svg' %}" class="reg_typ_ico px-3">
                    <p class="reg_type mt-2 ml-4">Sign up as a patient</p>
                </a>
                <a href="#" class="reg-container row pt-3 my-4 mx-auto">
                    <img src="{% static 'icons/teacher.svg' %}" class="reg_typ_ico px-3">
                    <p class="reg_type mt-2 ml-4">Sign up as a doctor</p>
                </a>
                <a href="#" class="reg-container row pt-3 my-4 mx-auto">
                    <img src="{% static 'icons/administrator.svg' %}" class="reg_typ_ico px-3">
                    <p class="reg_type mt-2 ml-4">Sign up as an admin</p>
                </a>

            </div>
            <div class="modal-footer">
                <p class="need-acnt text-center mt-2 mx-auto">
                    Have an account?
                    <a href="#" class="need-acnt-signup" type="button" data-toggle="modal" data-target="#loginModal" data-dismiss="modal" aria-label="Close">
                        Login
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
<!-- register modal end -->




  </body>
</html>


<style>
    body{
      font-family: 'Poppins', sans-serif;
    }
    a:hover{
        text-decoration: none;
    }
</style>


<!-- Table Sorting Library -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
<script src=" https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>

<script>
$(document).ready(function() {
    $('#jsDataTableLib').DataTable();
    $('#jsDataTableLib2').DataTable();
    $('#jsDataTableLib3').DataTable();
    $('#jsDataTableLib4').DataTable();
} );
</script>

templates/addBlog.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="col-xl-8 mx-auto">
    <div style="height: 30px;"></div>
    <h3 class="text-center">Add blogs</h3>
    <div style="height: 20px;"></div>


    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" name="title" placeholder="Enter title">
        </div>
        <div class="form-group">
            <label for="content">Body</label>
            <textarea class="form-control" name="body" rows="5"></textarea>
        </div>

        <div class="form-group">
            <label for="image">Image</label>
            <input type="file" class="form-control-file" name="picture">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    
    
</div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <title></title>

    <meta charset="UTF-8">

  	<!-- media queary support -->
  	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

  	<!-- Latest compiled and minified CSS -->
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

  	<!-- jQuery library -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  	<!-- Popper JS -->
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  	<!-- Latest compiled JavaScript -->
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  	<!-- animated css link -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>

  	<!-- font awsome css link -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  	<!-- poppins font link -->
  	<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>

  	<!-- roboto font link -->
  	<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>

  	<!-- custom css link -->
  	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

  </head>
  <body>

    <div class="container-fluid">
      <div class="row m-0 bg-light" style="padding-left: 90px; padding-right: 80px;padding-top: 10px;">
          <a href="{% url 'app:index' %}" style="font-size: 36px; font-weight: 700;">
            <span style="color:#3c97e8;">Hi</span>
            <span style="color:#9bdf46;">Blooger</span>
          </a>

        <div class="col-md-2 ml-auto">
            <div class="row m-0">
                <span class="mx-3"><img src="{% static 'imgs/phn.png' %}" style="max-height: 40px;"></span>
                <p>Call Us<br>99-222-333</p>
            </div>
        </div>

        <div class="col-md-3 ml-4">
            <div class="row m-0">
                <span class="mx-3"><img src="{% static 'imgs/address.png' %}" style="max-height: 40px;"></span>
                <p>Address<br>221B Baker Street London, Uk</p>
            </div>
        </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light py-3" style="padding-left: 80px;padding-right: 80px;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active mx-4">
              <a class="nav-link" href="{% url 'app:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mx-4">
              <a class="nav-link" href="{% url 'app:blogs' %}">Blog</a>
            </li>
            <li class="nav-item mx-4">
                <a class="nav-link" href="{% url 'app:students' %}">Meet Our Students</a>
            </li>
            <li class="nav-item mx-4">
                <a class="nav-link" href="{% url 'app:teachers' %}">Teachers and Admins</a>
            </li>
            <li class="nav-item mx-4">
                <a class="nav-link" href="#">About Us</a>
            </li>

            
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link mx-3" href="#">Hi {{request.user.username}}!</a>
            <li class="nav-item">
                <a href="{% url 'app:signout' %}" class="btn nav-link" style="background-color: #3c97e8; color:white; width:100px; height:40px; border-radius:40px;">Logout</a>
            </li>
            {% else %}
            <li class="nav-item" data-toggle="modal" data-target="#loginModal">
                <a href="#" class="btn nav-link" style="background-color: #3c97e8; color:white; width:100px; height:40px; border-radius:40px;">Login</a>
            </li>
            {% endif %}
        </ul>
            
        </div>
      </nav>



    {% block content %}

    {% endblock %}







    
<!-- login modal start -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title login-modal-title" id="loginModalLabel">Welcome back</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'app:signin' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>User name</label>
                        <input type="text" class="form-control" name="username" placeholder="User name">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>

                    <div style="height: 80px;"></div>

                    <p class="modal-forgorpass text-center">
                        <a href="#">Forgot password?</a>
                    </p>
                    <input type="submit" class="btn login-submit mt-2 ml-3" name="login" value="Login" style="background-color: #64B53B;">
                    <p class="need-acnt text-center mt-3">
                        Need an account?
                        <a href="#" class="need-acnt-signup" type="button" data-toggle="modal" data-target="#registerModal" data-dismiss="modal" aria-label="Close">
                            Sign up
                        </a>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- login modal end -->

<!-- register modal start -->
<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title reg-modal-title" id="registerModalLabel">Sign up</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body py-5">

                <form method="post" action="{% url 'app:signup' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>User name</label>
                        <input type="text" class="form-control" name="username" placeholder="User name">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label>Retype Password</label>
                        <input type="password" class="form-control" name="password2" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" name="email" placeholder="email">
                    </div>
                    <div class="form-group">
                        <label>Signup As</label>
                        <select name="userType" class="form-control">
                            <option value="Student">Student</option>
                            <option value="Teacher">Teacher</option>
                            <option value="Admin">Admin</option>
                        </select>
                    </div>

                    <input type="submit" class="btn login-submit mt-2 ml-3" name="login" value="Sign Up" style="background-color: #64B53B;">
                    
                </form>

            </div>
            <div class="modal-footer">
                <p class="need-acnt text-center mt-2 mx-auto">
                    Have an account?
                    <a href="#" class="need-acnt-signup" type="button" data-toggle="modal" data-target="#loginModal" data-dismiss="modal" aria-label="Close">
                        Login
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
<!-- register modal end -->




  </body>
</html>


<style>
    body{
      font-family: 'Poppins', sans-serif;
    }
    a:hover{
        text-decoration: none;
    }
</style>


<!-- Table Sorting Library -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
<script src=" https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>

<script>
$(document).ready(function() {
    $('#jsDataTableLib').DataTable();
    $('#jsDataTableLib2').DataTable();
    $('#jsDataTableLib3').DataTable();
    $('#jsDataTableLib4').DataTable();
} );
</script>

templates/blogDetails.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


{% if blogs %}
<div style="height: 20px;"></div>

<div class="col-xl-10 mx-auto">
    <img src="{{ blogs.picture.url }}" alt="Not Found" class="thumbnail my-2">
    <h4>{{blogs.title}}</h4>
    <div class="row m-0">
        <small>Created at: {{ blogs.created_at }}</small>
        <small class="ml-auto">Author: {{ blogs.author }}</small>
    </div>
    <hr>
    <p>{{ blogs.body }}</p>
</div>

{% endif %}


<style>
    .thumbnail {
        width: 40%;
        height: auto;
    }
</style>


{% endblock %}

templates/blogs.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-xl-10 mx-auto">
    <div style="height: 30px;"></div>
    <div class="row m-0">
        <h3 class="mx-auto">All blogs</h3>
        <a href="{% url 'app:addBlog' %}" class="btn btn-info">Add Blog</a>
    </div>
    <div style="height: 20px;"></div>
</div>

{% if blogs %}

<div class="col-xl-10 mx-auto">
    <table class="table table-striped" id ="jsDataTableLib">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Author Rank</th>
                
                <th scope="col">Date Created</th>
                <th scope="col">Read</th>
            </tr>
        </thead>
        <tbody>
            {% for i in blogs %}
            <tr>
                <th scope="row">{{ i.pk }}</th>
                <td>{{ i.title }}</td>
                <td>{{ i.author.username }}</td>
                <td>{{ i.author.userType }}</td>
                <td>{{ i.created_at }}</td>
                <td> <a href="{% url 'app:blogDetails' blog_id=i.pk %}" class="btn btn-info">Go!</a> </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}


{% endblock %}

templates/students.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}


{% if students %}

<div style="height: 30px;"></div>
<h3 class="text-center">All Students</h3>
<div style="height: 20px;"></div>

<div class="col-xl-10 mx-auto">
    <table class="table table-striped" id ="jsDataTableLib">
        <thead>
            <tr>
                <th scope="col">username</th>
                <th scope="col">Email</th>
                <th scope="col">User Type</th>
                <th scope="col">Varification Status</th>
                {% if request.user.is_superuser %}
                <th scope="col">Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for i in students %}
            <tr>
                <th scope="row">{{ i.username }}</th>
                <td>{{ i.email }}</td>
                <td>{{ i.userType }}</td>
                <td>{{ i.isVarified }}</td>
                {% if request.user.is_superuser %}
                    {% if not i.isVarified %}
                    <td><a href="{% url 'app:approve' user_id=i.pk %}" class="btn btn-success">Approve</a></td>
                    {% else %}
                    <td><a href="{% url 'app:refuse' user_id=i.pk %}" class="btn btn-warning">Refuse</a></td>
                    {% endif %}
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}


{% endblock %}

templates/teachers.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}



{% if teachers %}

<div style="height: 30px;"></div>
<h3 class="text-center">All Teachers</h3>
<div style="height: 20px;"></div>

<div class="col-xl-10 mx-auto">
    <table class="table table-striped" id ="jsDataTableLib">
        <thead>
            <tr>
                <th scope="col">username</th>
                <th scope="col">Email</th>
                <th scope="col">User Type</th>
                <th scope="col">Varification Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in teachers %}
            <tr>
                <th scope="row">{{ i.username }}</th>
                <td>{{ i.email }}</td>
                <td>{{ i.userType }}</td>
                <td>{{ i.isVarified }}</td>
                {% if not i.isVarified %}
                <td><a href="{% url 'app:approve' user_id=i.pk %}" class="btn btn-success">Approve</a></td>
                {% else %}
                <td><a href="{% url 'app:refuse' user_id=i.pk %}" class="btn btn-warning">Refuse</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}


{% if admins %}

<div style="height: 30px;"></div>
<h3 class="text-center">All Admins</h3>
<div style="height: 20px;"></div>

<div class="col-xl-10 mx-auto">
    <table class="table table-striped" id ="jsDataTableLib">
        <thead>
            <tr>
                <th scope="col">username</th>
                <th scope="col">Email</th>
                <th scope="col">User Type</th>
                <th scope="col">Varification Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in admins %}
            <tr>
                <th scope="row">{{ i.username }}</th>
                <td>{{ i.email }}</td>
                <td>{{ i.userType }}</td>
                <td>{{ i.isVarified }}</td>
                {% if not i.isVarified %}
                <td><a href="{% url 'app:approve' user_id=i.pk %}" class="btn btn-success">Approve</a></td>
                {% else %}
                <td><a href="{% url 'app:refuse' user_id=i.pk %}" class="btn btn-warning">Refuse</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}




{% endblock %}